[project]
name = 'Carbon-Credit-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.carbon-credit-marketplace]
path = 'contracts/carbon-credit-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.carbon-credit-token]
path = 'contracts/carbon-credit-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.carbon-offset-projects]
path = 'contracts/carbon-offset-projects.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
